# platform :ios, ‘7.0’
source 'https://github.com/CocoaPods/Specs.git'
pod 'MagicalRecord', '~> 2.2'
pod 'AFNetworking', '~> 2.5.0'
pod 'SDWebImage', '~> 3.7.1'
pod 'MBProgressHUD', '~> 0.9'
pod 'RDVTabBarController', '~> 1.1.9'
pod 'Toast', '~> 2.4'
pod 'FMDB', '~> 2.5'
pod 'ASIHTTPRequest', '~> 1.8.2'
pod 'MJRefresh','~> 1.3.7'
